experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: InBatch
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
model:
  name: JinaV4UniIR
  pretrained_model_dir: /data/LR1-UniIR/src/models/jina_v4t/jina_v4t.py
  short_name: jina_v4t
  size: large
retrieval_config:
  candidate_dir_name: null
  embed_dir_name: embed
  index_dir_name: indices
  qrel_dir_name: qrels
  query_dir_name: null
  raw_retrieval: false
  results_dir_name: retrieval_results
  retrieve_image_text_pairs: false
  test_datasets_config:
    correspond_cand_pools_name:
    - mscoco_task3_test
    - webqa_task1
    - UNION
    - UNION
    correspond_metrics_name:
    - Recall@1, Recall@5, Recall@10
    - Recall@1, Recall@5, Recall@10
    - Recall@1, Recall@5, Recall@10
    - Recall@1, Recall@5, Recall@10
    correspond_qrels_name:
    - mscoco_task3
    - webqa_task1
    - mscoco_task3
    - webqa_task1
    datasets_name:
    - mscoco_task3
    - webqa_task1
    - mscoco_task3
    - webqa_task1
    enable_retrieve: true
  train_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_retrieve: false
  val_datasets_config:
    correspond_cand_pools_name: null
    correspond_qrels_name: null
    datasets_name: null
    enable_retrieve: false
  write_to_tsv: true
